# **NumPy Array**

In [101]:
# Creating an array

import numpy as np 

a = np.array([1,2,3])
a

array([1, 2, 3])

In [102]:
# Multiplication of two arrays

import numpy as np 
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

a*b

array([ 6, 14, 24, 36, 50])

In [103]:
# It creates an array with 10 elements and fills all elements with the value zero.
np.zeros(10)

# It creates a 3x5 array and fills all elements with the value one.
np.ones((3,5))

# It creates a 3x5 array and fills all elements with the value 3.
np.full((3,5),3)

# It creates an array with numbers from 0 to 30 (inclusive), with a step of 3 between consecutive elements.
np.arange(0,31, 3)

# It creates an array of 10 evenly spaced numbers from 0 to 1 (inclusive).
np.linspace(0,1, 10)

# It creates a 3x4 array with random numbers sampled from a normal distribution with a mean of 10 and a standard deviation of 4.
np.random.normal(10,4, (3,4))

# It creates a 3x3 array with random integers ranging from 0 to 9 (inclusive).
np.random.randint(0,10, (3,3))

array([[3, 3, 2],
       [9, 3, 8],
       [6, 2, 1]])

# **Properties of a NumPy Array**

* **ndim**  : ndim attribute in numpy returns the number of dimensions (axes) of an array.
* **shape** : shape attribute in numpy returns the dimensions (size) of an array as a tuple.
* **size**  : size attribute in numpy returns the total number of elements in an array.
* **dtype** : dtype attribute in numpy returns the data type of the elements in an array.

In [110]:
# One Dimensional Array
# We create a numpy array with 10 elements and fill it with random integers ranging from 0 to 9.
# Afterward, we perform operations on this array's properties.

import numpy as np 
a = np.random.randint(10, size=10)

#ndim
a.ndim

#shape
a.shape

#size
a.size

#dtype
a.dtype

dtype('int32')

In [105]:
# Two Dimensional Array
# It creates a 3x5 array with random integers ranging from 0 to 9 (inclusive).
# Afterward, we perform operations on this array's properties.

import numpy as np
b = np.random.randint(10, size=(3,5))

#ndim
b.ndim

#shape
b.shape

#size
b.size

#dtype
b.dtype

dtype('int32')

### **Reshaping**
* "**Reshaping**" in numpy refers to changing the shape of an array without altering its data.

In [106]:
# This code creates a 1-dimensional array containing numbers from 1 to 9,
# and then reshapes it into a 3x3 two-dimensional array.

import numpy as np
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### **Concatenate**

* Numpy "**Concatenate**" means combining or joining two or more arrays along a specified axis.

In [107]:
# In the given code, three numpy arrays x, y, and z are created,
# and then they are concatenated into a single array using np.concatenate([x, y, z])

import numpy as np

x = np.array([1,2,3])
y = np.array([4,5,6])
z = np.array([7,8,9])

np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### **Axis**

* "**Axis**" in numpy is used to specify along which axis or dimension an operation should be performed on an array.
* **0 == Line**
* **1 == Column**

In [108]:
# This code concatenates arrays x and y along axis 0, resulting in a new array.
np.concatenate([x,y], axis = 0)

array([1, 2, 3, 4, 5, 6])

### **Splitting**
* Numpy "**Splitting**" refers to dividing an array into multiple smaller arrays along a specified axis or indices.


In [49]:
# One Dimensional Array
# In the given code, a numpy array x is created,
# and then it is split into three smaller arrays at the indices 3 and 5 using np.split(x, [3, 5]).

import numpy as np
x = np.array([1,2,3,99,99,3,2,1])
np.split(x, [3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [111]:
# Two Dimensional Array

import numpy as np
m = np.arange(16).reshape(4,4)

# Vertical horizontally
np.vsplit(m, [2])

# Dividing partition 
np.hsplit(m, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

### **Sorting**
* Numpy "**Sorting**" refers to arranging the elements of an array in ascending or descending order.

In [60]:
# In the given code, a numpy array v is created with elements [2, 1, 4, 3, 5],
# and then it is sorted in ascending order using np.sort(v).

import numpy as np 
v = np.array([2,1,4,3,5])
np.sort(v)

array([1, 2, 3, 4, 5])

### **Accessing elements with an index**

In [74]:
import numpy as np 
m = np.random.randint(10, size = (3,5))
m[0,0]=99
m[0,0]

99

### **Slicing**

* "**Slicing**" in numpy refers to extracting a portion of an array using specified ranges of indices.

In [82]:
import numpy as np 
a = np.arange(20,30)

a[0:3]
a[:3]
a[3:]
a[0::3]

array([20, 23, 26, 29])

### **Copy**

* NumPy "**Copy**" is used to create a deep copy of an array in numpy.

In [109]:
# In the given code, a new numpy array altB is created by making a deep copy of a subarray of 
# m that includes rows 0 to 2 (exclusive) and columns 0 to 1 (exclusive).

import numpy as np
m = np.random.randint(10, size = (5,5))
m

array([[2, 1, 8, 6, 6],
       [0, 0, 5, 2, 3],
       [0, 3, 0, 5, 3],
       [4, 6, 3, 3, 7],
       [5, 3, 2, 0, 4]])

### **Fancy Index** 
* "**Fancy Indexing**" refers to indexing an array using arrays of indices or boolean masks to access or modify specific elements.

In [88]:
# In the given code, a numpy array v is created with numbers from 0 to 27 (exclusive) with a step of 3,
# and then specific elements are selected from v using a list of indices [1, 3, 5] as v[bring].

import numpy as np 

v = np.arange(0,30,3)
bring = [1,3,5]
v[bring]

array([ 3,  9, 15])

### **Ufunc**

* Numpy "**Ufunc**" (universal function) refers to a function that operates element-wise on arrays, supporting broadcasting and enabling efficient numerical computations.

In [97]:
import numpy as np 
x = np.array([1,2,3,4,5])

# -1
np.subtract(x,1)

# +1
np.add(x,1)

# *5
np.multiply(x,5)

# /2
np.divide(x,2)

# x**3
np.power(x,3)



array([  1,   8,  27,  64, 125], dtype=int32)

### **Solving Two Unknown Equations with NumPy**

5 * x0 + x1 = 12 

x0 + 3 * x1 = 10 

In [100]:
import numpy as np 

a = np.array([[5,1] , [1,3]])
b = np.array([12 , 10])

x = np.linalg.solve(a,b)
x

array([1.85714286, 2.71428571])